server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: Center
          uri: http://localhost:8082
          predicates:
            - Path=/centers/**, 
        - id: Reservation
          uri: http://localhost:8083
          predicates:
            - Path=/reservations/**, 
        - id: Message
          uri: http://localhost:8084
          predicates:
            - Path=/messages/**, 
        - id: Payment
          uri: http://localhost:8085
          predicates:
            - Path=/payments/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Center
          uri: http://center:8080
          predicates:
            - Path=/centers/**, 
        - id: Reservation
          uri: http://reservation:8080
          predicates:
            - Path=/reservations/**, 
        - id: Message
          uri: http://message:8080
          predicates:
            - Path=/messages/**, 
        - id: Payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
